#!/bin/bash
# My first script

#alias proj="cd /home/ba/FAnalyzer/"

# Get the argument
table_name=("$@")

/usr/bin/python3 /home/ba/FAnalyzer/diskspacecheck.py $table_name
echo "Done running disk space check script"